name: 'untitled2'
version: 0.0.1
description: An absolute bare-bones web app.
#author: icecreamtoo <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'



#  my_dependency: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  shelf:
  shelf_route:
  sqljocky:
  shelf_cors:
  route_hierarchical: any
  json_object:

transformers:
- dart_to_js_script_rewriter
