name: db
version: 0.0.1
description: A simple console application.
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  shelf:
  shelf_route:
  sqljocky:
  shelf_cors:
  route_hierarchical: any
  json_object:
  jsonx:
  modern_charts:
  google_charts:
#  foo_bar: '>=1.0.0 <2.0.0'
